spring:
 application:
   name: admin-service
 boot:
   admin:
     discovery:
       enabled: true      
server:
 port: 9090
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka  # adapta al host/puerto de tu Eureka
   register-with-eureka: true
   fetch-registry: true
 instance:
   prefer-ip-address: true